[project]
name = "transient-heat-transfer-analysis-model"
version = "0.0.0"
description = "Demo m30ml project for conducting a transient heat transfer analysis"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "linkml==1.8.7",
    "pint>=0.24.4",
    "scipy>=1.15.2",
]
